---
swagger: '2.0'
info:
  title: API V1
  version: v1
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
definitions:
  finance_goal:
    type: object
    required:
    - id
    - attributes
    - relationships
    properties:
      id:
        type: string
        example: 19
      relationships:
        type: object
        required:
        - planedExpenses
        properties:
          planedExpenses:
            type: object
            required:
            - links
            properties:
              links:
                type: object
                required:
                - related
                properties:
                  related:
                    type: string
                    example: https://example.com/expenses
      attributes:
        type: object
        properties:
          paymentAmount:
            type: integer
            example: 1200
          incomeAmount:
            type: integer
            example: 1200
          startedAt:
            type: string
            example: '2020-02-15T12:31:11+03:00'
            format: date-time
          finishedAt:
            type: string
            example: '2020-02-15T12:31:11+03:00'
            format: date-time
          monthNumber:
            type: integer
            example: 12
        required:
        - paymentAmount
        - incomeAmount
        - startedAt
        - finishedAt
        - monthNumber
  planed_expense:
    type: object
    required:
    - id
    - attributes
    properties:
      id:
        type: string
        example: 19
      attributes:
        type: object
        properties:
          name:
            type: string
            example: Mikl
          amount:
            type: number
            example: 100
        required:
        - name
        - amount
  error_msg:
    type: object
    required:
    - errors
    properties:
      errors:
        type: array
        items:
          type: object
          required:
          - title
          properties:
            title:
              type: string
            message:
              type: string
paths:
  "/api/moneyboxes/{moneybox_id}/finance_goals":
    get:
      summary: Get list of goals
      tags:
      - goals
      produces:
      - application/json
      security:
      - api_key: []
      parameters:
      - name: moneybox_id
        type: integer
        in: path
        required: true
      responses:
        '200':
          description: Returns list
          schema:
            type: object
            required:
            - data
            properties:
              data:
                type: array
                items:
                  "$ref": "#/definitions/finance_goal"
        '401':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '404':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
  "/api/finance_goals/{id}":
    get:
      summary: Get goal
      tags:
      - goals
      produces:
      - application/json
      security:
      - api_key: []
      parameters:
      - name: id
        type: integer
        in: path
        required: true
      responses:
        '200':
          description: Returns goal info
          schema:
            type: object
            required:
            - data
            properties:
              data:
                "$ref": "#/definitions/finance_goal"
        '401':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '404':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
  "/api/finance_goals/{goal_id}/planed_expenses":
    get:
      summary: Get list of expenses
      tags:
      - Planed Expenses
      produces:
      - application/json
      security:
      - api_key: []
      parameters:
      - name: goal_id
        type: number
        in: path
        required: true
      responses:
        '200':
          description: Returns list
          schema:
            type: object
            required:
            - data
            properties:
              data:
                type: array
                items:
                  "$ref": "#/definitions/planed_expense"
        '401':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '404':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
    post:
      summary: Add new expenses
      tags:
      - Planed Expenses
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - api_key: []
      parameters:
      - name: goal_id
        type: number
        in: path
        required: true
      - name: params
        in: body
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
              example: Milk
            amount:
              type: number
              example: 100
          required:
          - name
          - amount
      responses:
        '201':
          description: Returns new expense
          schema:
            type: object
            required:
            - data
            properties:
              data:
                "$ref": "#/definitions/planed_expense"
        '401':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '404':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '400':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
  "/api/planed_expenses/{id}":
    patch:
      summary: Update expense
      tags:
      - Planed Expenses
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - api_key: []
      parameters:
      - name: id
        type: number
        in: path
        required: true
      - name: params
        in: body
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
              example: Milk
            amount:
              type: number
              example: 100
      responses:
        '200':
          description: Returns expense
          schema:
            type: object
            required:
            - data
            properties:
              data:
                "$ref": "#/definitions/planed_expense"
        '401':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '404':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
        '400':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
  "/tokens":
    post:
      summary: Get list of expenses
      tags:
      - Planed Expenses
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              example: test@test.org
            password:
              type: string
              example: qwerty
          required:
          - email
          - password
      responses:
        '200':
          description: Returns token
          schema:
            type: object
            properties:
              token:
                type: string
                example: some:token:jwt
        '401':
          description: Invalid credentials
          schema:
            "$ref": "#/definitions/error_msg"
