default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgresql://teachbase:teachbase@localhost/moneybox_development

test:
  <<: *default
  url: postgresql://teachbase:teachbase@localhost/moneybox_test

production:
  <<: *default
  database: moneybox_production
  username: moneybox
  password: <%= ENV['MONEYBOX_DATABASE_PASSWORD'] %>
