name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: login to heroku
        env:
          HEROKU_CREDENTIALS_EMAIL: ${{ secrets. HEROKU_CREDENTIALS_EMAIL }}
          HEROKU_CREDENTIALS_PASSWORD: ${{ secrets. HEROKU_CREDENTIALS_PASSWORD }}
          HEROKU_APP_NAME: ${{ secrets. HEROKU_APP_NAME }}
        run: |
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login ${HEROKU_CREDENTIALS_EMAIL}
              password ${HEROKU_CREDENTIALS_PASSWORD}
          machine git.heroku.com
              login ${HEROKU_CREDENTIALS_EMAIL}
              password ${HEROKU_CREDENTIALS_PASSWORD}
          EOF
          sudo apt-get -yqq install heroku
          heroku git:remote --app ${HEROKU_APP_NAME}
          git branch
          git remote
          git push heroku HEAD:refs/heads/master
          echo 'Deploy front'
