name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install and login heroku
        env:
          HEROKU_CREDENTIALS_EMAIL: ${{ secrets. HEROKU_CREDENTIALS_EMAIL }}
          HEROKU_CREDENTIALS_PASSWORD: ${{ secrets. HEROKU_CREDENTIALS_PASSWORD }}
          HEROKU_APP_NAME: ${{ secrets. HEROKU_APP_NAME }}
        run: |
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login ${HEROKU_CREDENTIALS_EMAIL}
              password ${HEROKU_CREDENTIALS_PASSWORD}
          machine git.heroku.com
              login ${HEROKU_CREDENTIALS_EMAIL}
              password ${HEROKU_CREDENTIALS_PASSWORD}
          EOF
          sudo apt-get -yqq install heroku
          heroku git:remote --app ${HEROKU_APP_NAME}
      - name: deploy backend
        run: |
          git push heroku HEAD:refs/heads/master
          heroku run rake db:migrate
      - name: deploy front
        env:
          FRON_DEPLOY_URL: ${{ secrets. FRON_DEPLOY_URL }}
        run: curl ${FRON_DEPLOY_URL}
