name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7.0
    - name: Build and test with Rake
      run: |
        ruby -v
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
